### ISSUE TITLE
example pictures links are broken

### ISSUE THREAD

**Issue by djacquel** [ResponsiveImagesCG/responsiveimages.org#67]
As of today, example pictures are broken. 
HTTP answer is *410 Gone* for all images on http://respimg.cdnconnect.com/

**Comment by marcoscaceres** [comment]
oh dear :(

**Comment by marcoscaceres** [comment]
@adamdbradley, any ideas where they went?

**Comment by Wilto** [comment]
Thaaat’s not good.

**Comment by marcoscaceres** [comment]
Pinged Adam on twitter too. I'm sure we will get that fixed quickly.

**Comment by adamdbradley** [comment]
Sorry about that, I just updated the links to point to the local files instead.

**Comment by marcoscaceres** [comment]
Thanks Adam for the fixes. I've pushed them to prod.
