### ISSUE TITLE
Blocked Mixed Content when accessing via HTTPS

### ISSUE THREAD

**Issue by anselmh** [ResponsiveImagesCG/responsiveimages.org#78]
When accessing the site via HTTPS, browsers block the CSS, scripts, partially images away as it’s served via HTTP. Reason is probably the Google mod_pagespeed optimizer messing up with the protocols.

Can someone fix this on the server, @marcoscaceres @wilto?

**Comment by marcoscaceres** [comment]
Argh... this is the fun part of transitioning to TLS :) Fixing.

**Comment by marcoscaceres** [comment]
Disabled mod_pagespeed on dreamhost.... will check again in 5 mins if fixed.

**Comment by marcoscaceres** [comment]
@anselmh can you confirm that it's working? Working on my side in Chrome, Firefox, and Safari.

**Comment by anselmh** [comment]
Thank you, works fine now :)

**Comment by yoavweiss** [comment]
Can we add https://w3c.github.io/webappsec/specs/upgrade/ to make sure this doesn't happen again with some other resources? (in supporting browsers)
