### ISSUE TITLE
https://gh.responsiveimages.org is broken.

### ISSUE THREAD

**Issue by Wilto** [ResponsiveImagesCG/responsiveimages.org#81]
And God only knows what other URLs.

The HTTPS transition for responsiveimages.org has been _way_ more trouble than it’s worth, considering that it is almost entirely redirects and a few static pages with no data that needs securing. If we can’t get this sorted out in a reliable way, I’m not sure what the benefit is compared to the cost.

**Comment by yoavweiss** [comment]
Not related to HTTPS. DNS trouble...

**Comment by marcoscaceres** [comment]
Sorry, I take full responsibility here. I wasn't as organized as I should
have been in checking the subdomains. I'll get on it soon. At least the
main site is ok...today:)

Anyway, learning experience and all that.

**Comment by marcoscaceres** [comment]
I've checked and renabled the following: 

 * bugs.responsiveimages.org
 * demos.responsiveimages.org
 * downloads.responsiveimages.org
 * gh.responsiveimages.org
 * list.responsiveimages.org
 * picture.responsiveimages.org
 * picturefill.responsiveimages.org
 * w3c.responsiveimages.org
 * wiki.responsiveimages.org
 * x-picture.responsiveimages.org 

What happened: 

CloudFlare (he he, I love starting this by blaming others) was supposed to automatically add all the old DNS records to itself when I did the migration... but for whatever reason, it a few didn't get migrated across. I've added the missing ones, including `gh.`, `list.`, `w3c.`.

**Comment by marcoscaceres** [comment]
Waiting for DNS record propagation for remaining links above...

**Comment by marcoscaceres** [comment]
All working :+1:
