### ISSUE TITLE
broken link: http://usecases.responsiveimages.org/

### ISSUE THREAD

**Issue by gruppjo** [ResponsiveImagesCG/responsiveimages.org#85]
Hi everybody:

On http://responsiveimages.org/ there's a link to the use-cases of each: `srcset` and `<picture>`. Unfortunately it points to a broken link.
![image](https://cloud.githubusercontent.com/assets/1370779/20274551/4512f954-aa95-11e6-81e2-f4b8b0d3fa78.png)

**Comment by marcoscaceres** [comment]
Thanks for reporting. Dreamhost recently moved servers and seems that this DNS entry broke. I've updated the DNS record for it, so hopefully should be back RSN.

**Comment by marcoscaceres** [comment]
Propagating... 

```Bash
; <<>> DiG 9.8.3-P1 <<>> usecases.responsiveimages.org +nostats +nocomments +nocmd
;; global options: +cmd
;usecases.responsiveimages.org.	IN	A
usecases.responsiveimages.org. 14399 IN	CNAME	responsiveimagescg.github.io.
responsiveimagescg.github.io. 3599 IN	CNAME	github.map.fastly.net.
github.map.fastly.net.	25	IN	A	151.101.100.133
```

**Comment by marcoscaceres** [comment]
works for me now...
