### ISSUE TITLE
Incorrect description for GRID SYSTEM demo 

### ISSUE THREAD

**Issue by dgg-trimit** [ResponsiveImagesCG/responsiveimages.org#86]
Hi, 

Not sure where to post this, so I guessed here; sorry if wrong :-)

The description for "GRID SYSTEM" (second demo at [https://responsiveimages.org/demos/]) is incorrect; it uses `<img/>` element with `srcset`attributes and not the `picture` element as stated.

**Comment by marcoscaceres** [comment]
@dgg-trimit, mind sending a PR?

**Comment by dgg-trimit** [comment]
@marcoscaceres done

**Comment by anselmh** [comment]
Done as per https://github.com/ResponsiveImagesCG/responsiveimages.org/pull/87. Thanks @dgg-trimit!

**Comment by marcoscaceres** [comment]
Thanks, will deploy soon.

**Comment by marcoscaceres** [comment]
deployed
